In [1]:
import numpy as np
from utils import radd

## Gauss Elimination: Pivoting Example

In [16]:
# tbt.m
n = 2
a = np.c_[np.r_[0.01, 1.], np.r_[-1.0, 0.01]]
b = np.c_[np.r_[1, 1]]
r = a ** (-1) * b
x = np.r_[0, 0]
m21 = a[1, 0] / a[0, 0]
a[1, 0] = 0
a[1, 1] = radd(a[1, 1], -m21 * a[0, 1], n)
b[1] = radd(b[1], -m21 * b[0], n)
x[1] = b[1] / a[1, 1]
x[0] = (radd(b[0], -a[0, 1] * x[1], n)) / a[0, 0]
x[:, None]

array([[ 0],
       [-1]])

In [17]:
a @ x[:, None], b

(array([[   1.],
        [-100.]]),
 array([[   1],
        [-100]]))

In [18]:
# tbt2.m
n = 1
a = np.c_[np.r_[1., 0.01], np.r_[0.01, -1.]]
b = np.c_[np.r_[1, 1]]
r = a ** (-1) * b
x = np.r_[0, 0]
m21 = a[1, 0] / a[0, 0]
a[1, 0] = 0
a[1, 1] = radd(a[1, 1], -m21 * a[0, 1], n)
b[1] = radd(b[1], -m21 * b[0], n)
x[1] = b[1] / a[1, 1]
x[0] = (radd(b[0], -a[0, 1] * x[1], n)) / a[0, 0]
x[:, None]

array([[ 1],
       [-1]])

In [19]:
a @ x[:, None], b

(array([[0.99],
        [1.  ]]),
 array([[1],
        [1]]))

## Gauss Elimination: Equation Scaling Example

In [20]:
n = 1
a = np.c_[np.r_[2, 1.], np.r_[-200, 0.01]]
b = np.c_[np.r_[200, 1]]
r = a ** (-1) * b
x = np.r_[0, 0]
m21 = a[1, 0] / a[0, 0]
a[1, 0] = 0
a[1, 1] = radd(a[1, 1], -m21 * a[0, 1], n)
b[1] = radd(b[1], -m21 * b[0], n)
x[1] = b[1] / a[1, 1]
x[0] = (radd(b[0], -a[0, 1] * x[1], n)) / a[0, 0]
x[:, None]

array([[ 0],
       [-1]])

In [21]:
a @ x[:, None], b

(array([[ 200.],
        [-100.]]),
 array([[ 200],
        [-100]]))

## Gauss Elimination: Effect of variable transform (variable scaling)

In [22]:
# tbt4.m
n = 2
a = np.c_[np.r_[1., 1.], np.r_[-1., 0.0001]]
b = np.c_[np.r_[100, 1]]
r = a ** (-1) * b
x = np.r_[0, 0]
m21 = a[1, 0] / a[0, 0]
a[1, 0] = 0
a[1, 1] = radd(a[1, 1], -m21 * a[0, 1], n)
b[1] = radd(b[1], -m21 * b[0], n)
x[1] = b[1] / a[1, 1]
x[0] = (radd(b[0], -a[0, 1] * x[1], n)) / a[0, 0]
x[:, None]

array([[   0],
       [-100]])

In [23]:
a @ x[:, None], b

(array([[ 100.],
        [-100.]]),
 array([[ 100],
        [-100]]))